# Generated by Django 6.0.6 on 2026-08-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_internships_liveprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveproject',
            name='abstract_file_1',
            field=models.FileField(blank=True, upload_to='abstracts/'),
        ),
        migrations.AddField(
            model_name='liveproject',
            name='abstract_file_2',
            field=models.FileField(blank=True, upload_to='abstracts/'),
        ),
        migrations.AddField(
            model_name='liveproject',
            name='abstract_file_3',
            field=models.FileField(blank=True, upload_to='abstracts/'),
        ),
        migrations.AddField(
            model_name='liveproject',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
